### PR TITLE
Proposed regexp enhancement host-digits, process-dashes and absent-pid

### PR DESCRIPTION
**Pull request by mhmeadows63**
Here is the requested PR covering the issues raised in vdemedes/syslog-parse#3

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Great, thanks! I hope you liked contributing for the first time :)

**Comment by mhmeadows63** [comment]
How does this new merge become the version that is delivered by `npm install syslog-parse` ?

**Comment by vadimdemedes** [comment]
I will release it today or tomorrow ;)

**Comment by mhmeadows63** [comment]
Ok, thanks.

I'm not sure why the npm page says `npm test` fails, could it be due to mocha's dependancy on depreciated jade/to-iso-string/minimatch ?

**Comment by mhmeadows63** [comment]
Oh bother, I just found another issue with process-name parsing - wpa_supplicant has an underscore that is not matched.

e.g. '<30>Aug  9 14:14:12 portal wpa_supplicant: wlan0: AP-STA-DISCONNECTED 01:23:45:67:89:ab'

**Comment by vadimdemedes** [comment]
@mhmeadows63 mind sending a follow up PR? :)

**Comment by mhmeadows63** [comment]
Ok, I just wanted your take on it.
Thanks for your encouragement, I'll try for tomorrow.
- Martin (Galaxy S4)  -------------------

-------- Original message --------

**Pull request merged**
