### PR TITLE
allow host-underscores and process-underscores

### PR DESCRIPTION
**Pull request by mhmeadows63**
switched regex to use \w instead of [a-z0-9] for host and process to permit underscores

### CODE REVIEW

**Comment by mhmeadows63** [comment]
@vdemedes Here we go, better late than never.

**Comment by vadimdemedes** [comment]
Thanks!

**Comment by vadimdemedes** [comment]
Released on npm as `syslog-parse@1.1.0`.

**Comment by mhmeadows63** [comment]
Adopted in-place of personal variant - many thanks

**Pull request merged**
