### PR TITLE
Break up big regex; Support process names with numbers, periods, and slashes

### PR DESCRIPTION
**Pull request by rentzsch**
The title about says it all :)

The main regex should be easier to understand, fix, and enhance now.

### CODE REVIEW

**Comment by rentzsch** [comment]
Hmm, I guess I'm using modern language features here that requires Node 6.

FWIW, [Node 6 becomes LTS this Saturday](https://github.com/nodejs/LTS). The Future Is Near.

**Comment by vadimdemedes** [comment]
@rentzsch Nope, you aren't, you just need to add `'use strict';` to the beginning of `index.js` and it'll work on v4 as well ;)

Thanks, PR looks good! After `use strict` is added, I'll merge it right away.

**Comment by rentzsch** [comment]
Ah yes I forgot about the 'use strict' requirement under node 4.x. I implemented your suggestion and now tests are passing, thanks.

**Comment by vadimdemedes** [comment]
Merged in via https://github.com/vdemedes/syslog-parse/commit/a333586c5999c0d6d2a9961d6b02b50dccbe5f06. Big thanks! 🎆

**Comment by vadimdemedes** [comment]
Published as `1.3.0`.

**Pull request closed without merging**
